### ISSUE TITLE
deb12.1 bump - 6.2.16-5 

### ISSUE THREAD

**Issue by wommy** [brunokc/pve-kernel-builder#12]
i havent noticed any issues, just a little confused on semver

also are your shutdown downs and reboots slow?
they were slow before the bump, after the patched  6.2.16-4

**Comment by brunokc** [comment]
For some reason the kernel version and ABI version got out of step (they used to be the same). For instance, as of today, the latest version is 6.2.16-6 and the latest ABI version is 6.2.16-5. 🤷‍♂️ Because of that bump, a new version should be available later today, once the job kicks in.

I haven't started using the 6.2 kernel line yet. I'll probably upgrade to Proxmox 8 soon and then I'll check on that.

**Comment by wommy** [comment]
one thing nice about it is the kernel bump just reinstalled
the old one, so nothing broke

**Comment by wommy** [comment]
also the new version has been out for 3 days or so, so the action isnt seeing it
kinda why i made an issue

**Comment by brunokc** [comment]
> one thing nice about it is the kernel bump just reinstalled the old one, so nothing broke

I'm confused. Are you saying installing the latest ([pve-kernel-6.2.16-4-pve-relaxablermrr_6.2.16-5_amd64.deb](https://github.com/brunokc/pve-kernel-builder/releases/download/v1.0.4/pve-kernel-6.2.16-4-pve-relaxablermrr_6.2.16-5_amd64.deb)) doesn't do anything?



> also the new version has been out for 3 days or so, so the action isnt seeing it kinda why i made an issue

Are you referring to 6.2.16-5? According to their [git repository](https://git.proxmox.com/?p=pve-kernel.git;a=summary) (which is what I check), it only came out about 10 hours ago:

<img width="521" alt="image" src="https://github.com/brunokc/pve-kernel-builder/assets/1355373/c62738aa-8de1-4871-9770-b2b855617199">

**Comment by wommy** [comment]
> I'm confused. Are you saying installing the latest ([pve-kernel-6.2.16-4-pve-relaxablermrr_6.2.16-5_amd64.deb](https://github.com/brunokc/pve-kernel-builder/releases/download/v1.0.4/pve-kernel-6.2.16-4-pve-relaxablermrr_6.2.16-5_amd64.deb)) doesn't do anything?

what im saying is when i got the update, it didnt install the new one, it reinstalled your deb

> Are you referring to 6.2.16-5? According to their [git repository](https://git.proxmox.com/?p=pve-kernel.git;a=summary) (which is what I check), it only came out about 10 hours ago:

i definitely waited at least 24 hours before i updated, waiting for your repo to snag it, and probably another 12 before i made the issue,
something could be wrong in my system tho, my servers been down for a few days

**Comment by brunokc** [comment]
> what im saying is when i got the update, it didnt install the new one, it reinstalled your deb

I see it now, thanks. Interesting though. Was the update offered for the version 6.2.16-5 then? Not sure it should have reverted to my custom deb.
 
> i definitely waited at least 24 hours before i updated, waiting for your repo to snag it, and probably another 12 before i made the issue, something could be wrong in my system tho, my servers been down for a few days

Yeah, not sure what to say. I go by what their git repo says. If everything goes well, a new build should be triggered in about 10-20min (it triggers daily at around 2:45AM UTC/7:45PM PST but it's not precise)

**Comment by brunokc** [comment]
...and, of course, the build wasn't kicked off. Not sure why -- the workflow did find the new version as expected, saved it, but failed to invoke the build workflow (it says it was skipped)🤷‍♂️.

https://github.com/brunokc/pve-kernel-builder/actions/runs/5664091716/job/15346819098

I might have to kick it off manually.

**Comment by brunokc** [comment]
There's a weird behavior that feels like a Github Actions/Workflow bug. I'm trying to get help on that.

https://github.com/orgs/community/discussions/61792

**Comment by wommy** [comment]
yeah i wish this github actions stuff more was much clear
hopefully the next gen of tools/docs simplifies & clarifies this by an order of magnitude
but glad you found a decent channel for questions and youre getting some feedback

i appreciate being kept in the loop

**Comment by brunokc** [comment]
This issue was fixed by commit 0aeb61b2fc985c44aaffbe75f554bbefb78232c5. In the process, I'll be posting new 6.2.16 kernel debs shortly.
