### ISSUE TITLE
Release build 5.15.108-1-pve naming

### ISSUE THREAD

**Issue by Brunhilde** [brunokc/pve-kernel-builder#13]
Hi,

just noticed that ne release build for 7.4 [5.15.108-1-pve](https://github.com/brunokc/pve-kernel-builder/releases/tag/v1.0.3) is not named "relaxablermrr". Does it contain the patch?

**Comment by brunokc** [comment]
Thank you for the heads up. Not sure how I missed that. Let me check to see if it's just a packaging problem or if the automation missed applying the patch.

**Comment by brunokc** [comment]
Sorry for the delay. 

It looks like the patch that changes the version to include the `relaxablermrr` suffix failed to apply, but the actual patch did apply, so it should work. I'm working on a fix.

**Comment by brunokc** [comment]
This issue was fixed by commit 0aeb61b2fc985c44aaffbe75f554bbefb78232c5. I'll post new debs shortly.

**Comment by brunokc** [comment]
Release updated with new debs: https://github.com/brunokc/pve-kernel-builder/releases/tag/v1.0.3

Thank you for raising this.
