### ISSUE TITLE
AArch64 support

### ISSUE THREAD

**Issue by kenji21** [brunokc/pve-kernel-builder#14]
Does a support of aarch64 is achievable (even if not officially supported) ?

https://github.com/jiangcuo/Proxmox-Port?tab=readme-ov-file#interesting-thing states:

![Screenshot 26](https://github.com/brunokc/pve-kernel-builder/assets/1105089/2363e81a-fdb2-4738-a684-2465264f5fd6)

related to https://forum.proxmox.com/threads/proxmox-on-aarch64-arm64.121925/
which points to https://github.com/pimox/pimox7 and https://github.com/jiangcuo/Proxmox-Arm64

**Comment by brunokc** [comment]
It might, assuming no issues compiling the kernel for it. Having said that, you'd probably want the newer (6.x) kernels compiled for arch64, not the 5.x series from here (the ones still being produced by this project), no?

From the looks of it, jiangcuo has things working already, although I'm not sure why they are running kernel 5.15 with Proxmox 8.x (it comes with kernel 6.2). Proxmox kernel 6.2 should already have the "relaxable RMRR" patch included, so all you need to do is enable it. How would kernel 5.15 be useful here?

**Comment by kenji21** [comment]
As he started support with proxmox 7.2, he needed the 5.x kernel

**Comment by brunokc** [comment]
So why not just move to kernel 6.x? He'll want that eventually, right?

**Comment by brunokc** [comment]
Stale issue.
