### ISSUE TITLE
Alternate RMRR Kernel repo

### ISSUE THREAD

**Issue by Aterfax** [brunokc/pve-kernel-builder#9]
Not really an issue, just wanted to highlight that https://github.com/Aterfax/relax-intel-rmrr exists which I am (relatively) actively maintaining. Nice to see its not just me plugging this gap!

**Comment by brunokc** [comment]
Hi there, 

Thanks for reaching out. I see you've been doing this for some time and you have had a lot of traction. Are you planning to release newer builds?

This started as a way to build the kernel with the RMRR patch and then became a more general "drop your patches here and we'll build it" kind of project. Then it became more about learning GitHub actions and workflows (I'm new to this but it's been really annoying to debug -- isn't there a way to try workflow changes locally before pushing them up?). At this point though, I'm focusing my attention on getting this patch incorporated into Proxmox itself -- it makes little sense to be chasing the kernel like this. Please take a look at https://bugzilla.proxmox.com/show_bug.cgi?id=4707 and let's see if we can put a bit more pressure to get this incorporated. 

Thanks again for the heads up.

**Comment by Aterfax** [comment]
> Hi there,
> 
> Thanks for reaching out. I see you've been doing this for some time and you have had a lot of traction. Are you planning to release newer builds?
> 
> This started as a way to build the kernel with the RMRR patch and then became a more general "drop your patches here and we'll build it" kind of project. Then it became more about learning GitHub actions and workflows (I'm new to this but it's been really annoying to debug -- isn't there a way to try workflow changes locally before pushing them up?). At this point though, I'm focusing my attention on getting this patch incorporated into Proxmox itself -- it makes little sense to be chasing the kernel like this. Please take a look at https://bugzilla.proxmox.com/show_bug.cgi?id=4707 and let's see if we can put a bit more pressure to get this incorporated.
> 
> Thanks again for the heads up.

I'm planning on keeping releasing until I either retire my HP Gen 8 or Proxmox mainlines the patching. To that end, I'll voice some support on https://bugzilla.proxmox.com/show_bug.cgi?id=4707
